### ISSUE TITLE
BaNaNas not being updated with new content in-game

### ISSUE THREAD

**Issue by NyanGoat** [OpenTTD/BaNaNaS#140]
It does not seem like uploads are being updated in this database anymore.

New uploads that show on bananas.openttd.org are not showing in-game:
![image](https://github.com/OpenTTD/BaNaNaS/assets/109810800/4d060491-dc23-4b7f-a1e9-d205bc3e0636)

And updated versions are also not being updated ingame:
![image](https://github.com/OpenTTD/BaNaNaS/assets/109810800/f379af07-6d4d-4c62-a396-80888133df47)

The last update to this database was 2023-06-12, before the infra changes.

**Comment by TrueBrain** [comment]
There was a bug in the quantum un-entanglement machine which caused some hyper-sonic vibrations in the slipstream window allocator. All is fixed now, and all uploads will show up in-game in a moment!

**Comment by TrueBrain** [comment]
@evepoi as a FYI, by my account you uploaded 9 versions of your DTS NewGRF today. The first 4 sadly enough are not recorded properly due to a bug in the system, and won't be available in-game. On the other hand, the better news: the last 5 you uploaded are available and working fine.

My assumption here is that it isn't actually a problem that those first 4 are lost, given there are 5 newer versions available; but if I am wrong, please do let me know, and I will see what I can do for you.

Either way: sorry for the trouble!
